### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by wshankles** [OttPeterR/addon-babybuddy#43]
Using the UI to setup the integration it fails to connect. I am using http://192.168.50.XXX, left the port at 8000, left path blank, and using the API key from the addon.

**Comment by OttPeterR** [comment]
Have you tried using 'localhost'?
Edit: 127.0.0.1 might also work

Edit 2: I should have asked this first, but does the add-on work as expected if you access it from that ip:port? also does it work in the ingress as well? I'd recommend using 127.0.0.1 since that'd stay connected if your HA's IP were to change.

**Comment by wshankles** [comment]
Thanks for the help. localhost didn't work and 127.0.0.1. The add-on did work going to ip:port but only after I toggled the network under the configuration and set it to 8000. After that it still didn't work until I did a combo of using 127.0.0.1 and manually setting the port to 8000.

**Comment by OttPeterR** [comment]
oh yes, sorry for not specifying, you also need the port when setting up the integration. I'll close out this issue since you're good to go! 😄
