### ISSUE TITLE
How to access via Android App?

### ISSUE THREAD

**Issue by no1wafer** [OttPeterR/addon-babybuddy#44]
Hi,
I have installed 1.15.1 Baby Buddy addon onto my Home Assistant as ingress.
But is there a way to access it via the Android App?
I don't know what should I put in to the server address URL.
Thanks!

**Comment by OttPeterR** [comment]
Do you mean the Home Assistant Android App?
For that you can either set an ingress user or put in your domain into the trusted domains option, more info here:
https://github.com/OttPeterR/addon-babybuddy/blob/main/babybuddy/DOCS.md
For that trusted domain, if ingress errors it should tell you on the error page.

**Comment by no1wafer** [comment]
Thanks for your reply.
I mean is to access the BB Add-on via the BB Android App.
I have raised my question there instead.
Thank you!

**Comment by cdubz** [comment]
I think it makes sense in either place, really... please cross-reference when you post in the Android repo. I'll test this myself, as well.

**Comment by cdubz** [comment]
@no1wafer for the record I was able to test this successfully... just took a hell of a long time 😄

The server address URL for the Android app should be the external address of the Baby Buddy instance in HA. Using an internal address may also work but I figured that would be less useful.

The documentation you'll need to check out is:
- https://github.com/OttPeterR/addon-babybuddy#additional-setup-for-https-via-nginx-using-your-own-domain
- https://github.com/hassio-addons/addon-nginx-proxy-manager/blob/main/proxy-manager/DOCS.md
- https://theprivatesmarthome.com/how-to/set-up-nginx-proxy-manager-in-home-assistant/

It's a hell of a process but mostly just because of the HA configuration stuff for setting up NGINX and external access.
